nginx-proxy:
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
db:
  image: mongo
  ports:
    - 27017
api:
  build: ../RenBotApi/
  ports: 
    - "3000:3000"
  links:
    - db
web:
  build: .
  volumes:
    - .:/app
  links:
    - db